/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 14.0.0-1ubuntu1 -fPIC -Os) */

(* hdlname = "\\CARRY4WHOLE" *)
(* top =  1  *)
(* src = "carry4whole.v:1.1-7.10" *)
module CARRY4WHOLE(CO, O, CI, CYINIT, DI, S);
  (* src = "carry4whole.v:1.46-1.48" *)
  wire _00_;
  (* src = "carry4whole.v:1.33-1.35" *)
  wire _01_;
  (* src = "carry4whole.v:1.33-1.35" *)
  wire _02_;
  (* src = "carry4whole.v:1.33-1.35" *)
  wire _03_;
  (* src = "carry4whole.v:1.33-1.35" *)
  wire _04_;
  (* src = "carry4whole.v:1.50-1.56" *)
  wire _05_;
  (* src = "carry4whole.v:1.70-1.72" *)
  wire _06_;
  (* src = "carry4whole.v:1.70-1.72" *)
  wire _07_;
  (* src = "carry4whole.v:1.70-1.72" *)
  wire _08_;
  (* src = "carry4whole.v:1.70-1.72" *)
  wire _09_;
  (* src = "carry4whole.v:1.37-1.38" *)
  wire _10_;
  (* src = "carry4whole.v:1.37-1.38" *)
  wire _11_;
  (* src = "carry4whole.v:1.37-1.38" *)
  wire _12_;
  (* src = "carry4whole.v:1.37-1.38" *)
  wire _13_;
  (* src = "carry4whole.v:1.74-1.75" *)
  wire _14_;
  (* src = "carry4whole.v:1.74-1.75" *)
  wire _15_;
  (* src = "carry4whole.v:1.74-1.75" *)
  wire _16_;
  (* src = "carry4whole.v:1.74-1.75" *)
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  (* src = "carry4whole.v:1.46-1.48" *)
  input CI;
  wire CI;
  (* src = "carry4whole.v:1.33-1.35" *)
  output [3:0] CO;
  wire [3:0] CO;
  (* src = "carry4whole.v:1.50-1.56" *)
  input CYINIT;
  wire CYINIT;
  (* src = "carry4whole.v:1.70-1.72" *)
  input [3:0] DI;
  wire [3:0] DI;
  (* src = "carry4whole.v:1.37-1.38" *)
  output [3:0] O;
  wire [3:0] O;
  (* src = "carry4whole.v:1.74-1.75" *)
  input [3:0] S;
  wire [3:0] S;
  assign _18_ = ~_08_;
  assign _19_ = ~_16_;
  assign _20_ = ~_09_;
  assign _21_ = ~_17_;
  assign _22_ = ~_05_;
  assign _23_ = ~_00_;
  assign _24_ = ~_06_;
  assign _25_ = ~_14_;
  assign _26_ = ~_15_;
  assign _27_ = ~_07_;
  assign _28_ = ~(_22_ & _23_);
  assign _29_ = ~_28_;
  assign _30_ = ~(_14_ & _29_);
  assign _31_ = ~(_24_ & _25_);
  assign _32_ = ~(_30_ & _31_);
  assign _01_ = ~_32_;
  assign _33_ = ~(_15_ & _32_);
  assign _34_ = ~(_26_ & _27_);
  assign _35_ = ~(_33_ & _34_);
  assign _02_ = ~_35_;
  assign _36_ = ~(_16_ & _35_);
  assign _37_ = ~(_18_ & _19_);
  assign _38_ = ~(_36_ & _37_);
  assign _03_ = ~_38_;
  assign _39_ = ~(_17_ & _38_);
  assign _40_ = ~(_20_ & _21_);
  assign _41_ = ~(_39_ & _40_);
  assign _04_ = ~_41_;
  assign _42_ = ~(_25_ & _28_);
  assign _10_ = ~(_30_ & _42_);
  assign _43_ = ~(_26_ & _01_);
  assign _11_ = ~(_33_ & _43_);
  assign _44_ = ~(_19_ & _02_);
  assign _12_ = ~(_36_ & _44_);
  assign _45_ = ~(_21_ & _03_);
  assign _13_ = ~(_39_ & _45_);
  assign _08_ = DI[2];
  assign CO[1] = _02_;
  assign _16_ = S[2];
  assign CO[2] = _03_;
  assign _09_ = DI[3];
  assign _17_ = S[3];
  assign CO[3] = _04_;
  assign _05_ = CYINIT;
  assign _00_ = CI;
  assign O[0] = _10_;
  assign _06_ = DI[0];
  assign _14_ = S[0];
  assign O[1] = _11_;
  assign O[2] = _12_;
  assign O[3] = _13_;
  assign CO[0] = _01_;
  assign _15_ = S[1];
  assign _07_ = DI[1];
endmodule
